name: "Build and Publish"

on:
  create:
    tags:
      - '[0-9].*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ModuleBuilder
      
      - name: build
        shell: pwsh
        env:
          TOKEN: ${{ secrets.PS_GALLERY_KEY }}
        run: |
          ./build.ps1 -semver $env:GITHUB_REF.split('/')[2]
          Publish-Module -Path . -NuGetApiKey $env:TOKEN -Repository PSGallery -verbose
