name: "Build and Publish"

on:
  create:
    tags:
      - '[0-9].*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ModuleBuilder

      - name: Set Env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: build
        shell: pwsh
        env:
          TOKEN: ${{ secrets.PS_GALLERY_KEY }}
        run: |
          ./build.ps1
          gci -recurse
          Publish-Module -Path . -NuGetApiKey $env:TOKEN -Repository PSGallery
